# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/curies.rb'

Hoe.new('curies', Curies::VERSION) do |p|
  # p.rubyforge_name = 'blahx' # if different than lowercase project name
  # p.developer('FIX', 'FIX@example.com')
end

# vim: syntax=Ruby
